---
title: "Row Orientation"
output: 
  flexdashboard::flex_dashboard:
    theme: lumen
runtime: shiny
---

```{r global, include=FALSE}
source('1_PAGE_1.R', encoding="utf-8")
library(flexdashboard)
```


Page 1 {data-orientation=rows}
===================================== 

Column {.sidebar}
-----------------------------------------------------------------------

Waiting time between eruptions and the duration of the eruption for the
Old Faithful geyser in Yellowstone National Park, Wyoming, USA.

```{r}
# selectInput("n_breaks", label = "Number of bins:",
#             choices = c(10, 20, 35, 50), selected = 20)
# 
# sliderInput("bw_adjust", label = "Bandwidth adjustment:",
#             min = 0.2, max = 2, value = 1, step = 0.2)
```

Row {data-height=300}
-------------------------------------
    
### Linked Value Box
    
```{r}
renderValueBox({
  valueBox(sum_cap_mil_last, 
           icon = "fa-trash",
           color = ifelse(sum_cap_mil_last > 10, "warning", "primary"))
})
```

### Chart 2
    
```{r}
```
    
### Chart 3

```{r}
```

### Chart 4

```{r}
```
   
Row
-------------------------------------

### Chart 5

```{r}
dygraph(term_chart('close'))
```

Row
-------------------------------------
    
### Chart 6
    
```{r}
```

### Chart 7
    
```{r}
```
    
### Chart 8

```{r}
```

Page 2 {data-orientation=column}
===================================== 

Column {.sidebar}
-----------------------------------------------------------------------

Waiting time between eruptions and the duration of the eruption for the
Old Faithful geyser in Yellowstone National Park, Wyoming, USA.

```{r}
# selectInput("n_breaks", label = "Number of bins:",
#             choices = c(10, 20, 35, 50), selected = 20)
# 
# sliderInput("bw_adjust", label = "Bandwidth adjustment:",
#             min = 0.2, max = 2, value = 1, step = 0.2)
```

Row
-------------------------------------
    
### Chart 1
    
```{r}
```

### Chart 2
    
```{r}
```
    
### Chart 3

```{r}
```

### Chart 4

```{r}
```
   
Row
-------------------------------------

### Chart 5

```{r}
```

Row
-------------------------------------
    
### Chart 6
    
```{r}
```

### Chart 7
    
```{r}
```
    
### Chart 8

```{r}
```